#!/usr/bin/env python
import sys
import os
import platform
import getpass

from PyQt5 import QtCore, QtGui, QtWebKit, QtWidgets, QtWebKitWidgets

class Commands(QtCore.QObject):
    """Simple class to be sent its instance to JavaScript global context."""

    @QtCore.pyqtSlot(str)
    def showMessage(self, msg):
        """Open a message box and display a message."""
        QtWidgets.QMessageBox.information(None, "Some title", msg)

    """System user property."""
    whoami = QtCore.pyqtProperty(str, fget=lambda x: getpass.getuser())

    """Python version property."""
    version = QtCore.pyqtProperty(str, fget=lambda x: platform.python_version())

def main():
    app     = QtWidgets.QApplication(sys.argv)
    webView = QtWebKitWidgets.QWebView()
    custom  = Commands()

    webView.page().mainFrame().addToJavaScriptWindowObject("Python", custom)

    path = os.path.abspath(".")
    webView.load(QtCore.QUrl("file://%s/index.html" % path))

    window = QtWidgets.QMainWindow()
    window.setCentralWidget(webView)
    window.show()

    sys.exit(app.exec_())

if __name__ == "__main__":
    main()